//
// LoginWithCustomIDResponseDataUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginWithCustomIDResponseDataUser: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var displayId: String?
    public var displayName: String?
    public var createdAt: String?

    public init(id: String? = nil, displayId: String? = nil, displayName: String? = nil, createdAt: String? = nil) {
        self.id = id
        self.displayId = displayId
        self.displayName = displayName
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "Id"
        case displayId = "DisplayId"
        case displayName = "DisplayName"
        case createdAt = "CreatedAt"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(displayId, forKey: .displayId)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

