//
// LoginwithCustomID.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginwithCustomID: Codable, JSONEncodable, Hashable {

    public var customId: String?
    public var token: String?
    public var createAccount: Bool?
    public var projectID: String?

    public init(customId: String? = nil, token: String? = nil, createAccount: Bool? = nil, projectID: String? = nil) {
        self.customId = customId
        self.token = token
        self.createAccount = createAccount
        self.projectID = projectID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customId = "CustomId"
        case token = "Token"
        case createAccount = "CreateAccount"
        case projectID = "ProjectID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customId, forKey: .customId)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(createAccount, forKey: .createAccount)
        try container.encodeIfPresent(projectID, forKey: .projectID)
    }
}

