//
// NotFound.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NotFound: Codable, JSONEncodable, Hashable {

    public var statusCode: Int?
    public var message: String?

    public init(statusCode: Int? = nil, message: String? = nil) {
        self.statusCode = statusCode
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case statusCode
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(statusCode, forKey: .statusCode)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

